### ISSUE TITLE
Enable necessary plugins for merge

### ISSUE THREAD

**Issue by hishutup** [matortheeternal/merge-plugins#81] opened 2015-12-29 05:06 UTC
I think it would be a nice feature if I could enable only the plugins required for a merge on the plugin selection window. I tend to right click on the Merge column, here is an image of what I mean... http://bit.ly/1YKv4Vt

**Comment by matortheeternal** [comment] 2015-12-29 05:08
Duplicate of #75

**Closed as completed by matortheeternal** 2015-12-29 05:08 UTC
Labels: duplicate
